version: 2
jobs:
  build:
    branches:
      ignore:
        - master
    docker:
      - image: futtetennista/hakyll:4.12.5.1
    steps:
      - add_ssh_keys:
          fingerprints:
            - "81:fc:9f:8a:77:ae:81:ba:0b:3c:25:26:6d:b4:79:fd"
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - stack-{{ checksum "stack.yaml" }}-{{ checksum "website.cabal" }}
            - stack-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: |
            stack --no-terminal setup
            stack --no-terminal build --dependencies-only -j1 --fast
      - save_cache:
          name: Cache Dependencies
          key: stack-{{ checksum "stack.yaml" }}-{{ checksum "website.cabal" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - run:
          name: Build Site App
          command: stack --no-terminal build
      - run:
          name: Generate Static Site
          command: |
            stack exec site clean
            stack exec site build
      - store_artifacts:
          path: _site
          destination: built_site
      - run:
          name: Publish GitHub Pages
          command: |
            echo "Now setting up git"
            git config user.name  'CircleCI'
            git config user.email 'job@circleci.com'
            echo "Switch to master"
            git checkout master
            echo "Remove the current site stuff ..."
            rm -r `ls -a | grep -v "^\.$\|^\.\.$\|^\.git$\|^\.gitignore$\|^_site$"`
            echo "... and replace it with what's in _site."
            mv ./_site/* .
            rm -r _site
            echo "The new site contents is:"
            ls -al
            echo "Adding generated files and committing"
            git add .
            git commit -m "publish $CIRCLE_SHA1 [ci skip]"
            echo "Pushing to master"
            git push origin master
